[package]
name = "clr"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { workspace = true }
assert_cmd = { workspace = true }

[[bin]]
name = "false"
path = "src/bin/false.rs"

[[bin]]
name = "true"
path = "src/bin/true.rs"

[[bin]]
name = "clr"
path = "src/main.rs"
