[workspace]
members = ["clr", "rvrs", "gato"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
anyhow = "1"
pretty_assertions = "1.4"
assert_cmd = "2"
predicates = "3"
clap = "4"
