[package]
name = "rvrs"
version.workspace = true
edition.workspace = true

[dependencies]
clap = { workspace = true, features = ["cargo"] }

[dev-dependencies]
anyhow = { workspace = true }
assert_cmd = { workspace = true }
predicates = { workspace = true }
