[package]
name = "depsdot"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["cargo", "derive"] }
assert_cmd = "2"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }