[package]
name = "depsdot"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["cargo", "derive"] }
assert_cmd = { workspace = true }
toml = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }