name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
      - uses: actions-rust-lang/rustfmt@v1
      - run: cargo clippy
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: |
          set -eEuxo pipefail
          cargo llvm-cov test --fail-under-functions 80 | tee cov.txt
          echo "COVERAGE=$(cat cov.txt | grep "TOTAL" | awk '{print $4}' | sed 's/%//g')" >> $GITHUB_ENV
      - name: cov-badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.THEBADGE }}
          gistID: d86fe4168b61872f7e63d85ce3c9fea6
          filename: cov.json
          label: coverage
          message: ${{env.COVERAGE}}%
          valColorRange: ${{env.COVERAGE}}
          minColorRange: 0
          maxColorRange: 100
       
