name: ci
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt
      - uses: actions-rust-lang/rustfmt@v1
      - run: cargo clippy
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: |
          set -eEuxo pipefail
          cargo llvm-cov test --fail-under-functions 80


# Using this action: https://github.com/actions-rust-lang/setup-rust-toolchain?tab=readme-ov-file#example-workflow
# I found here https://github.com/rust-lang/rustup/issues/3409#issuecomment-1890491688
